<?php

use Drupal\Core\Hook\Attribute\LegacyHook;

/**
 * @file
 * Contains tripal_chado.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Config\FileStorage;

require_once 'src/api/tripal_chado.schema.api.php';
require_once 'src/api/tripal_chado.custom_tables.api.php';
require_once 'src/api/tripal_chado.mviews.api.php';
require_once 'src/api/tripal_chado.query.api.php';
require_once 'src/api/tripal_chado.variables.api.php';
require_once 'src/api/tripal_chado.organism.api.php';
require_once 'src/api/tripal_chado.db.api.php';
require_once 'src/api/tripal_chado.cv.api.php';
require_once 'src/api/tripal_chado.property.api.php';
require_once 'src/api/tripal_chado.phylotree.api.php';
require_once 'src/api/tripal_chado.phylotree_newick.api.php';
require_once 'src/legacyFunctions.php';

require_once 'src/api/tripal_chado.viewsdata.inc';

/**
 * Implements hook_help().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\tripal_chado\Hook\TripalChadoHooks in
 * tripal_chado/src/Hook/TripalChadoHooks.php.
 */
#[LegacyHook]
function tripal_chado_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service('tripal_chado.hooks')->help($route_name, $route_match);
}

/**
 * Implements hook_config_schema_info_alter().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\tripal_chado\Hook\TripalChadoHooks in
 * tripal_chado/src/Hook/TripalChadoHooks.php.
 */
#[LegacyHook]
function tripal_chado_config_schema_info_alter(&$definitions) {
  \Drupal::service('tripal_chado.hooks')->configSchemaInfoAlter($definitions);
}

/**
 * Implements hook_rebuild().
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\tripal_chado\Hook\TripalChadoHooks in
 * tripal_chado/src/Hook/TripalChadoHooks.php.
 */
#[LegacyHook]
function tripal_chado_rebuild() {
  \Drupal::service('tripal_chado.hooks')->rebuild();
}

/**
 * Implements hook_form_alter
 *
 * This legacy hook is only run for Drupal < 11, and is replaced by class
 * Drupal\tripal_chado\Hook\TripalChadoHooks in
 * tripal_chado/src/Hook/TripalChadoHooks.php.
 */
#[LegacyHook]
function tripal_chado_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  \Drupal::service('tripal_chado.hooks')->formAlter($form, $form_state, $form_id);
}
