<?php

/**
 * @file
 * Contains tripal_chado.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Config\FileStorage;

require_once 'src/api/tripal_chado.schema.api.inc';
require_once 'src/api/tripal_chado.custom_tables.api.inc';
require_once 'src/api/tripal_chado.query.api.inc';
require_once 'src/api/tripal_chado.variables.api.inc';
require_once 'src/api/tripal_chado.organism.api.inc';
require_once 'src/api/tripal_chado.db.api.inc';
require_once 'src/api/tripal_chado.cv.api.inc';
require_once 'src/legacyFunctions.php';

/**
 * Implements hook_help().
 */
function tripal_chado_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tripal_chado module.
    case 'help.page.tripal_chado':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Chado integration for Tripal.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_rebuild().
 */
function tripal_chado_rebuild() {

  //
  // Make sure the Views are present.
  //
  $storage = \Drupal::entityTypeManager()->getStorage('view');
  $dir = drupal_get_path('module', 'tripal_chado');
  $fileStorage = new FileStorage($dir);

  // The chado_custom_tables view.
  $view = $storage->load('chado_custom_tables');
  if (!$view) {
    $config = $fileStorage->read('config/install/views.view.chado_custom_tables');
    $view = $storage->create($config);
    $view->save();
  }

  // The chado_materialized_views view.
  $view = $storage->load('chado_materialized_views');
  if (!$view) {
    $config = $fileStorage->read('config/install/views.view.chado_materialized_views');
    $view = $storage->create($config);
    $view->save();
  }
}