<?php
/**
 * @file
 * Contains functions used to install/uninstall tripal_chado.
 */

use \Drupal\Core\Config\FileStorage;
use \Drupal\Core\Database\Database;
use \Drupal\Core\Utility\UpdateException;
use \Drupal\Component\Serialization\Yaml;
use \Drupal\field\Entity\FieldConfig;
use \Drupal\tripal_chado\Entity\ChadoTermMapping;
use \Drupal\tripal\TripalVocabTerms\TripalTerm;

/**
 * Implements hook_install().
 */
function tripal_chado_install($is_syncing) {
  // Reserves Chado common schemas in 'reserved_schema_patterns' settings.
  $config = \Drupal::service('config.factory')
    ->getEditable('tripal.settings')
  ;
  $reserved_schema_patterns = $config->get('reserved_schema_patterns') ?? [];
  $reserved_schema_patterns['frange'] = 'feature range (chado)';
  $reserved_schema_patterns['genetic_code'] = 'genetic code (chado)';
  $reserved_schema_patterns['so'] = 'sequence ontology (chado)';
  $config->set('reserved_schema_patterns', $reserved_schema_patterns)->save();

  $test_schema_base_names = $config->get('test_schema_base_names') ?? [];
  $test_schema_base_names['chado'] = '_test_chado';
  $config->set('test_schema_base_names', $test_schema_base_names)->save();

}

/**
 * Implements hook_uninstall().
 */
function tripal_chado_uninstall() {
  // Unreserves Chado common schemas in 'reserved_schema_patterns' settings.
  $config = \Drupal::service('config.factory')
    ->getEditable('tripal.settings')
  ;
  $reserved_schema_patterns = $config->get('reserved_schema_patterns') ?? [];
  unset($reserved_schema_patterns['frange']);
  unset($reserved_schema_patterns['genetic_code']);
  unset($reserved_schema_patterns['so']);
  $config->set('reserved_schema_patterns', $reserved_schema_patterns)->save();
}

/**
 * Implementation of hook_schema().
 *
 * @ingroup tripal_chado
 */
function tripal_chado_schema() {
  $schema = [];

  $schema['chado_installations'] = tripal_chado_chado_installations_schema();
  $schema['chado_migrations'] = tripal_chado_chado_migrations_schema();
  $schema['tripal_custom_tables'] = tripal_chado_tripal_custom_tables_schema();
  $schema['tripal_mviews'] = tripal_chado_tripal_mviews_schema();

  // Add tables to integrate the independant Tripal Vocabularies to Chado terms.
  $schema['chado_tripalvocab'] = tripal_chado_chado_vocab();
  $schema['chado_tripalvocabspace'] = tripal_chado_chado_vocabidspace();
  $schema['chado_tripalterm'] = tripal_chado_chado_term();

  // Add tables supporting the Tripal Storage.
  $schema['tripal_cv_obo'] = tripal_chado_tripal_cv_obo_schema();

  return $schema;
}

/**
 * Table definition for the tripal_cv_obo table used by the OBO loader.
 */
function tripal_chado_tripal_cv_obo_schema() {
  return [
    'fields' => [
      'obo_id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE
      ],
      'name' => [
        'type' => 'varchar',
        'length' => 255
      ],
      'path'  => [
        'type' => 'varchar',
        'length' => 1024
      ],
    ],
    'indexes' => [
      'tripal_cv_obo_idx1' => ['obo_id'],
    ],
    'primary key' => ['obo_id'],
  ];
}

/**
 * Returns the Drupal Schema API array for the chado_installations table.
 */
function tripal_chado_chado_installations_schema() {
  return [
    'fields' => [
      'install_id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'schema_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'version' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'created' => [
        'type' => 'varchar',
        'length' => 255,
      ],
      'updated' => [
        'type' => 'varchar',
        'length' => 255,
      ],
    ],
    'indexes' => [
      'schema_name' => ['schema_name'],
    ],
    'primary key' => ['install_id'],
  ];
}

/**
 * Returns the Drupal Schema API array for the chado_installations table.
 */
function tripal_chado_chado_migrations_schema() {
  return [
    'fields' => [
      'migration_id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'job_id' => [
        'type' => 'int',
        'description' => 'The job_id of the TripalJob this migration was applied during.',
        'not null' => TRUE,
      ],
      'install_id' => [
        'type' => 'int',
        'description' => 'The install_id of the Tripal-managed chado installation/schema this migration was applied to.',
        'not null' => TRUE,
      ],
      'version' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'filename' => [
        'type' => 'text',
        'not null' => FALSE,
      ],
      'applied_on' => [
        'type' => 'varchar',
        'length' => 255,
      ],
      'success' => [
        'type' => 'int',
        'size' => 'tiny',
      ],
    ],
    'unique keys' => [
      'migration' => ['install_id', 'version'],
    ],
    'indexes' => [
      'status' => ['applied_on', 'success'],
    ],
    'foreign keys' => [
      'chado_installations' => [
        'table' => 'chado_installations',
        'columns' => [
          'install_id' => 'install_id'
        ],
      ],
    ],
    'primary key' => ['migration_id'],
  ];
}

/**
 * Links Tripal Vocabularies to Chado cvs.
 */
function tripal_chado_chado_vocab() {
  return [
    'fields' => [
      'mapping_id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'schema_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'cv_id' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
      'tripalvocab_id' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
    ],
    'indexes' => [
      'chado' => ['schema_name', 'cv_id'],
      'tripal' => ['tripalvocab_id'],
    ],
    'primary key' => ['mapping_id'],
  ];
}

/**
 * Links Tripal Vocabulary IDSpaces to Chado dbs.
 */
function tripal_chado_chado_vocabidspace() {
  return [
    'fields' => [
      'mapping_id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'schema_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'db_id' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
      'tripalvocabspace_id' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
    ],
    'indexes' => [
      'chado' => ['schema_name', 'db_id'],
      'tripal' => ['tripalvocabspace_id'],
    ],
    'primary key' => ['mapping_id'],
  ];
}

/**
 * Links Tripal Vocabularies to Chado cvs.
 */
function tripal_chado_chado_term() {
  return [
    'fields' => [
      'mapping_id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'schema_name' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'cvterm_id' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
      'tripalterm_id' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
    ],
    'indexes' => [
      'chado' => ['schema_name', 'cvterm_id'],
      'tripal' => ['tripalterm_id'],
    ],
    'primary key' => ['mapping_id'],
  ];
}

/**
 * Describes the tripal_mviews table.
 */
function tripal_chado_tripal_mviews_schema() {
  return array(
    'fields' => array(
      'mview_id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE
      ),
      'table_id' => array(
        'type' => 'int',
        'not null' => True,
        'description' => 'The custom table ID'
      ),
      'name' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE
      ),
      'query' => array(
        'type' => 'text',
        'size' => 'normal',
        'not null' => TRUE
      ),
      'last_update' => array(
        'type' => 'int',
        'not null' => FALSE,
        'description' => 'UNIX integer time'
      ),
      'status' => array(
        'type' => 'text',
        'size' => 'normal',
        'not null' => FALSE
      ),
      'comment' => array(
        'type' => 'text',
        'size' => 'normal',
        'not null' => FALSE
      ),
    ),
    'indexes' => array(
      'mview_id' => array('mview_id')
    ),
    'unique keys' => array(
      'table_id' => array('table_id'),
    ),
    'primary key' => array('mview_id'),
  );
}

/**
 * Describes the Tripal Custom Tables (tripal_custom_tables) table.
 * This keeps track of tables created by Tripal and stored in chado.
 */
function tripal_chado_tripal_custom_tables_schema() {
  return [
    'fields' => array(
      'table_id' => array(
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE
      ),
      'table_name' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE
      ),
      'schema' => array(
        'type' => 'text',
        'not null' => TRUE
      ),
      'locked' => array(
        'type' => 'int',
        'size' => 'tiny',
        'default' => 0,
        'description' => 'Set to true if this custom table is not for end-users to manage, but for the Tripal module.'
      ),
      'chado' => array(
        'type' => 'varchar',
        'length' => 64,
        'not null' => TRUE,
        'description' => 'The name of the Chado schema where this table exists.'
      ),
    ),
    'indexes' => array(
      'table_id' => array('table_id'),
    ),
    'primary key' => array('table_id'),
    'foreign keys' => array(
      'tripal_mviews' => array(
        'table' => 'tripal_mviews',
        'columns' => array(
          'mview_id' => 'mview_id'
        ),
      ),
    ),
  ];
}

/**
 * Helper function for any time we have to re-load a chado field
 *
 * @param array $upgradable_types
 *   A list of one or more chado fields
 * @param array $upgradable_properties
 *   A list of one or more properties to re-load
 * @param bool $update_only
 *   If TRUE then only update existing properties,
 *   if FALSE then we can also add a property if it does not exist.
 */
function tripal_chado_field_reload(array $upgradable_types, array $upgradable_properties, bool $update_only) {
  try {
    $messenger = \Drupal::messenger();
    $entity_type = 'tripal_entity';

    $manager = \Drupal::entityDefinitionUpdateManager();
    $schema = \Drupal::database()->schema();
    $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
    $field_map = \Drupal::service('entity_field.manager')->getFieldMap();
    $fields = $field_map[$entity_type];
    $n_added = 0;
    $n_updated = 0;

    foreach ($fields as $field_name => $field_def) {
      $id = $field_def['type'];
      if (in_array($id, $upgradable_types, TRUE)) {
        $field_storage_definition = $manager->getFieldStorageDefinition($field_name, $entity_type);
        if ($field_storage_definition) {
          $field_schema = $field_storage_definition->getSchema();
          $table_mapping = $storage->getTableMapping([$field_name => $field_storage_definition]);
          $table_names = $table_mapping->getDedicatedTableNames();
          $columns = $table_mapping->getColumnNames($field_name);

          foreach ($table_names as $table_name) {
            $table_exists = $schema->tableExists($table_name);
            if ($table_exists) {
              $messenger->addMessage(t("Updating properties for Drupal table \"@table_name\", field \"@field_name\"",
                  ['@table_name' => $table_name, '@field_name' => $field_name]));
              foreach ($upgradable_properties as $property) {
                $field_exists = $schema->fieldExists($table_name, $columns[$property]);
                if ($field_exists) {
                  $schema->changeField($table_name, $columns[$property], $columns[$property], $field_schema['columns'][$property]);
                  $n_updated++;
                }
                elseif (!$update_only) {
                  $schema->addField($table_name, $columns[$property], $field_schema['columns'][$property]);
                  $n_added++;
                }
              }
              $manager->updateFieldStorageDefinition($field_storage_definition);
            }
          }
        }
      }
    }
    if ($update_only) {
      $messenger->addMessage(t("Updated @n_updated properties",
          ['@n_updated' => $n_updated]));
    }
    else {
      $messenger->addMessage(t("Added @n_added properties, updated @n_updated properties",
          ['@n_added' => $n_added, '@n_updated' => $n_updated]));
    }
  }
  catch (\Exception $e) {
    throw new UpdateException('Could not update property: ' . $e->getMessage());
  }
}

/**
 * Reloads content type collections from their YAML files.
 *
 * @param array $collection_names
 *   The names of the collections to reload, valid values are
 *   ['expression', 'general', 'genetic', 'genomic', 'germplasm'].
 *
 * @return void
 *   No return value.
 */
function updateContentTypeCollections(array $collection_names): void {
  /** @var \Drupal\Core\Config\StorageInterface $active_storage */
  $active_storage = \Drupal::service('config.storage');
  $config_dir = __DIR__ . '/config/install';
  $source = new FileStorage($config_dir);
  foreach ($collection_names as $collection) {
    $entitytype_collection_id = 'tripal.tripalentitytype_collection.' . $collection . '_chado';
    $field_collection_id = 'tripal.tripalfield_collection.' . $collection . '_chado';
    $active_storage->write($entitytype_collection_id, $source->read($entitytype_collection_id));
    $active_storage->write($field_collection_id, $source->read($field_collection_id));
  }
}

/**
 * Reinstalls a specified content type collection.
 *
 * @param string $contentTypeCollection
 *   The name of the content type collection, e.g. "general".
 *
 * @return void
 *   No return value.
 */
function reloadContentTypeCollection(string $contentTypeCollection): void {
  // Reload the content type collection yaml into Drupal storage.
  updateContentTypeCollections([$contentTypeCollection]);

  // Reinstall the specified content type collection.
  // Any new bundles or fields will be created.
  $content_type_service = \Drupal::service('tripal.tripalentitytype_collection');
  $content_type_service->install([$contentTypeCollection . '_chado']);
}

/**
 * Reads a YAML file and adds the specified fields.
 *
 * @param string $yaml_path
 *   Path to the YAML file to parse.
 * @param array $field_names
 *   One or more fields to add.
 */
function addFieldFromYaml(string $yaml_path, array $field_names) {
  /** @var \Drupal\tripal\Services\TripalFieldCollection $fields_service **/
  $fields_service = \Drupal::service('tripal.tripalfield_collection');
  /** @var \Drupal\Core\Entity\EntityTypeManager $entity_type_manager **/
  $entity_type_manager = \Drupal::entityTypeManager();
  $fields = Yaml::decode(file_get_contents($yaml_path));
  foreach ($fields['fields'] as $field) {
    if (in_array($field['name'], $field_names)) {
      // Only add the field if its bundle exists
      $bundle = $field['content_type'];
      /** @var \Drupal\tripal\Entity\TripalEntityType $entity_type **/
      $entity_type = $entity_type_manager->getStorage('tripal_entity_type')->load($bundle);
      if ($entity_type) {
        $fields_service->addBundleField($field);
      }
    }
  }
}

/**
 * Adds third party settings for Tripal content types to Chado base tables.
 */
function tripal_chado_update_10401() {
  $settings = [
    // Generic content types.
    'organism' => 'organism',
    'analysis' => 'analysis',
    'project' => 'project',
    'study' => 'study',
    'contact' => 'contact',
    'pub' => 'pub',
    'protocol' => 'protocol',
    // Expression content types.
    'biosample' => 'biomaterial',
    'assay' => 'assay',
    'array_design' => 'arraydesign',
    // Genetic expression types.
    'genetic_map' => 'featuremap',
    'QTL' => 'feature',
    'sequence_variant' => 'feature',
    'genetic_marker' => 'feature',
    'phenotypic_marker' => 'feature',
    // Germplasm types.
    'germplasm' => 'stock',
    'breeding_cross' => 'stock',
    'germplasm_variety' => 'stock',
    'ril' => 'stock',
    // Genomic types.
    'gene' => 'feature',
    'mrna' => 'feature',
    'phylotree' => 'phylotree',
    'physical_map' => 'featuremap',
    'dna_library' => 'library',
    'genome_assembly' => 'analysis',
    'genome_annotation' => 'analysis',
    'genome_project' => 'project'
  ];

  /** @var \Drupal\Core\Entity\EntityTypeManager $entity_type_manager **/
  $entity_type_manager = \Drupal::entityTypeManager();
  foreach ($settings as $bundle => $chado_base_table) {
    /** @var \Drupal\tripal\Entity\TripalEntityType $entity_type **/
    $entity_type = $entity_type_manager->getStorage('tripal_entity_type')->load($bundle);
    if ($entity_type) {
      $entity_type->setThirdPartySetting('tripal', 'chado_base_table', $chado_base_table);
      $entity_type->save();
    }
  }
}

/**
 * Updates missing mapping of CV terms to some chado table columns.
 * Note: tripal_chado_update_10402 has been renumbered to
 * tripal_chado_update_10408 by PR 1927
 */

/**
 * Updates entity_id properties added to linking fields in PR 1782
 * Note: tripal_chado_update_10403 has been renumbered to
 * tripal_chado_update_10405 by PR 1865
 */

/**
 * Adds or updates several properties added to the
 * chado_sequence_coordinates_default field in PR 1861
 */
function tripal_chado_update_10404() {
  // This update only modifies a single field type.
  $upgradable_types = ['chado_sequence_coordinates_default'];
  $upgradable_properties = ['uniquename', 'fkey', 'srcfeature_id',
      'fmin', 'is_fmin_partial', 'fmax', 'is_fmax_partial',
      'strand', 'phase', 'residue_info', 'locgroup', 'rank'];
  tripal_chado_field_reload($upgradable_types, $upgradable_properties, FALSE);
}

/**
 * Updates entity_id properties added to linking fields in PR 1782 and PR 1865
 * This is the same as former tripal_chado_update_10403 but we need to run it again
 */
function tripal_chado_update_10405() {
  try {
    $messenger = \Drupal::messenger();

    $new_property = 'entity_id';
    // This is the list of Chado fields needing an entity_id
    $upgradable_types = [
      'chado_analysis_type_default',
      'chado_array_design_type_default',
      'chado_assay_type_default',
      'chado_biomaterial_type_default',
      'chado_contact_type_default',
      'chado_feature_type_default',
      'chado_featuremap_type_default',
      'chado_organism_type_default',
      'chado_project_type_default',
      'chado_protocol_type_default',
      'chado_pub_type_default',
      'chado_stock_type_default',
      'chado_study_type_default',
    ];
    $entity_type = 'tripal_entity';

    $manager = \Drupal::entityDefinitionUpdateManager();
    $schema = \Drupal::database()->schema();
    $storage = \Drupal::entityTypeManager()->getStorage($entity_type);
    $field_map = \Drupal::service('entity_field.manager')->getFieldMap();
    $fields = $field_map[$entity_type];
    $n_added = 0;
    $n_updated = 0;

    foreach ($fields as $field_name => $field_def) {
      $id = $field_def['type'];
      if (in_array($id, $upgradable_types, TRUE)) {
        $field_storage_definition = $manager->getFieldStorageDefinition($field_name, 'tripal_entity');
        if ($field_storage_definition) {
          $field_schema = $field_storage_definition->getSchema();
          $table_mapping = $storage->getTableMapping([$field_name => $field_storage_definition]);
          $table_names = $table_mapping->getDedicatedTableNames();
          $columns = $table_mapping->getColumnNames($field_name);

          foreach ($table_names as $table_name) {
            $table_exists = $schema->tableExists($table_name);
            if ($table_exists) {
              $field_exists = $schema->fieldExists($table_name, $columns[$new_property]);
              if ($field_exists) {
                $messenger->addMessage(t("Updating entity id in Drupal table \"@table_name\", field \"@field_name\"",
                    ['@table_name' => $table_name, '@field_name' => $field_name]));
                $schema->changeField($table_name, $columns[$new_property], $columns[$new_property], $field_schema['columns'][$new_property]);
                $n_updated++;
              }
              else {
                $messenger->addMessage(t("Adding entity id to Drupal table \"@table_name\", field \"@field_name\"",
                    ['@table_name' => $table_name, '@field_name' => $field_name]));
                $schema->addField($table_name, $columns[$new_property], $field_schema['columns'][$new_property]);
                $n_added++;
              }
            }
          }
        }
        $manager->updateFieldStorageDefinition($field_storage_definition);
      }
    }
    $messenger->addMessage(t("Added @n_added entity id properties, updated @n_updated entity id properties",
        ['@n_added' => $n_added, '@n_updated' => $n_updated]));
  }
  catch (\Exception $e) {
    throw new UpdateException('Could not add entity id to fields: ' . $e->getMessage());
  }
}

/**
 * Adds missing 'delete_if_empty' setting to the 'linker_synonym_fkey_id'
 * property in the 'chado_synonym_type_default' field, PR 1958
 */
function tripal_chado_update_10406() {
  $upgradable_types = ['chado_synonym_type_default'];
  $upgradable_properties = ['linker_synonym_fkey_id'];
  tripal_chado_field_reload($upgradable_types, $upgradable_properties, TRUE);
}

/**
 * Adds third party settings for content types that have multiple
 * content types derived from one base table. PR 1991
 */
function tripal_chado_update_10407() {

  try {
    $messenger = \Drupal::messenger();
    $bundleManager = \Drupal::service('entity_type.bundle.info');
    $entityFieldManager = \Drupal::service('entity_field.manager');
    $entityTypeManager = \Drupal::entityTypeManager();

    // Add missing additional type fields in yaml for the two featuremap bundles
    addFieldFromYaml(__DIR__ . '/config/install/tripal.tripalfield_collection.genetic_chado.yml', ['genetic_map_type']);
    addFieldFromYaml(__DIR__ . '/config/install/tripal.tripalfield_collection.genomic_chado.yml', ['physical_map_type']);

    // Add third party settings for bundle type using fixed_value term
    $entity_type_id = 'tripal_entity';
    $bundle_info = $bundleManager->getBundleInfo($entity_type_id);
    foreach (array_keys($bundle_info) as $bundle) {
      $fields = $entityFieldManager->getFieldDefinitions($entity_type_id, $bundle);
      foreach ($fields as $field) {
        $field_type = $field->getType();
        if ($field_type == 'chado_additional_type_type_default') {
          $fixed_value = $field->getSetting('fixed_value');
          if ($fixed_value) {
            $entity_type = $entityTypeManager->getStorage('tripal_entity_type')->load($bundle);
            if (!$entity_type->getThirdPartySetting('tripal', 'bundle_type_column')) {
              $term_parts = explode(':', $fixed_value, 2);
              $entity_type->setThirdPartySetting('tripal', 'bundle_type_table', $term_parts[0]);
              $entity_type->setThirdPartySetting('tripal', 'bundle_type_column', $term_parts[1]);
              $entity_type->save();
              $messenger->addMessage(t("Added entity third party setting for bundle @bundle term @fixed_value",
                  ['@bundle' => $bundle, '@fixed_value' => $fixed_value]));
            }
          }
        }
      }
    }
  }
  catch (\Exception $e) {
    throw new UpdateException('Could not add third party settings: ' . $e->getMessage());
  }
}

/**
 * Updates missing mapping of CV terms to some chado table columns. PR 1927
 * This is the same as former tripal_chado_update_10402, but here we are
 * also adding a new cvterm local:lineageex
 */
function tripal_chado_update_10408() {
  try {
    $messenger = \Drupal::messenger();

    // create the local:lineageex term if it does not exist
    $buddy_service = \Drupal::service('tripal_chado.chado_buddy');
    $cvterm_buddy = $buddy_service->createInstance('chado_cvterm_buddy', []);
    $cvterm_buddy->upsertCvterm(['cvterm.name' => 'lineageex',
                                 'cvterm.definition' => 'Extended taxonomic lineage used by NCBI',
                                 'cv.name' => 'local',
                                 'dbxref.accession' => 'lineageex',
                                 'db.name' => 'local'], []);

    $id = 'config/install/tripal.tripal_content_terms.chado_content_terms';
    ChadoTermMapping::refreshMapping($id);
    $messenger->addMessage('Reloaded Chado content terms');

    $id = 'config/install/tripal_chado.chado_term_mapping.core_mapping';
    ChadoTermMapping::refreshMapping($id);
    $messenger->addMessage('Reloaded Chado term mapping');
  }
  catch (\Exception $e) {
    throw new UpdateException('Could not reload Chado terms and mappings: ' . $e->getMessage());
  }
}

/**
 * Sets publication 'title' and 'pyear' fields as non-required, to be
 * consistent with chado. PR 2029
 */
function tripal_chado_update_10409() {
  try {
    $messenger = \Drupal::messenger();
    $field_ids = ['tripal_entity.pub.pub_title', 'tripal_entity.pub.pub_pyear'];
    foreach ($field_ids as $field_id) {
      /** Drupal\field\Entity\FieldConfig **/
      $field = FieldConfig::load($field_id);
      $required = $field->isRequired();
      if ($required) {
        $field->setRequired(FALSE);
        $field->save();
        $messenger->addMessage("Changed field $field_id to be not required");
      }
    }
  }
  catch (\Exception $e) {
    throw new UpdateException('Could not set title and publication year required setting: ' . $e->getMessage());
  }
}

/**
 * Corrects duplicated terms for some fields in yaml files.
 * PR 2079
 */
function tripal_chado_update_10410() {
  try {
    $messenger = \Drupal::messenger();

    // Adds a new CV term
    $buddy_service = \Drupal::service('tripal_chado.chado_buddy');
    $cvterm_buddy = $buddy_service->createInstance('chado_cvterm_buddy', []);
    $term_values = [
      'db.name' => 'NCIT',
      'cv.name' => 'ncit',
      'dbxref.accession' => 'C16493',
      'cvterm.name' => 'Data Source',
      'cvterm.definition' => 'The person or authoritative body who provided the information.',
    ];
    $chado_cvterm_record = $cvterm_buddy->upsertCvterm($term_values, []);
    $term_values = [
      'db.name' => 'SIO',
      'cv.name' => 'SIO',
      'dbxref.accession' => '001377',
      'cvterm.name' => 'versioned dataset',
      'cvterm.definition' => 'a versioned dataset is a dataset with a particular release date or release number.',
    ];
    $chado_cvterm_record = $cvterm_buddy->upsertCvterm($term_values, []);

    $update_list = [
      'tripal_entity.analysis.analysis_source:SIO:001377',
      'tripal_entity.analysis.analysis_source_version:NCIT:C16493',
      'tripal_entity.pub.pub_type:rdfs:type',
      'tripal_entity.array_design.array_design_substrate_type:EFO:0005522',
      'tripal_entity.array_design.array_design_platform_type:NCIT:C45378',
      'tripal_entity.genome_annotation.genome_annotation_src_version:NCIT:C16493',
      'tripal_entity.genome_annotation.genome_annotation_src_name:SIO:001377',
      'tripal_entity.genome_assembly.genome_assembly_source_version:NCIT:C16493',
      'tripal_entity.genome_assembly.genome_assembly_source_name:SIO:001377',
    ];
    foreach ($update_list as $update_item) {
      $parts = explode(':', $update_item);
      /** Drupal\field\Entity\FieldConfig **/
      $field = FieldConfig::load($parts[0]);
      if ($field) {
        $settings = $field->getSettings();
        $old_term = $settings['termIdSpace'] . ':' . $settings['termAccession'];
        $new_term = $parts[1] . ':' . $parts[2];
        if ($old_term != $new_term) {
          $settings['termIdSpace'] = $parts[1];
          $settings['termAccession'] = $parts[2];
          $field->setSettings($settings);
          $field->save();
          $messenger->addMessage("Changed term for field $parts[0] from $old_term to $new_term");
        }
      }
    }
  }
  catch (\Exception $e) {
    throw new UpdateException('Could not update chado fields: ' . $e->getMessage());
  }
}

/**
 * Moves several custom CVs, if present, to the local CV.
 */
function tripal_chado_update_10411() {
  // Transfer of CVs was done by PR 1727. This hook added by PR 2081
  $obsolete_cvs = [
    'organism_property', 'analysis_property', 'tripal_phylogeny',
    'featuremap_units', 'featurepos_property', 'featuremap_property',
    'study_property', 'nd_experiment_types', 'nd_geolocation_property',
    'tripal_analysis', 'library_property', 'library_type', 'project_property',
  ];

  try {
    $messenger = \Drupal::messenger();
    $chado = \Drupal::service('tripal_chado.database');

    $query = $chado->select('1:cv', 'cv');
    $query->condition('name', 'local', '=');
    $query->fields('cv', ['cv_id']);
    $local_cv = $query->execute()->fetchField();
    if (!$local_cv) {
      throw new UpdateException('Could not perform update, "local" CV is not present');
    }

    $n_transferred = 0;
    $n_removed = 0;
    foreach ($obsolete_cvs as $obsolete_cv) {
      $query = $chado->select('1:cv', 'cv');
      $query->condition('name', $obsolete_cv, '=');
      $query->fields('cv', ['cv_id']);
      $cv_id = $query->execute()->fetchField();

      // Only update if the CV exists
      if ($cv_id) {
        $query = $chado->update('1:cvterm');
        $query->fields(['cv_id' => $local_cv]);
        $query->condition('cv_id', $cv_id, '=');
        $count = $query->execute();
        if ($count) {
          $messenger->addMessage(t('Transferred @count records from CV "@from" to the "local" CV',
              ['@count' => $count, '@from' => $obsolete_cv]));
          $n_transferred += $count;
        }
        $query = $chado->delete('1:cv');
        $query->condition('name', $obsolete_cv, '=');
        $query->execute();
        $n_removed++;
      }
    }
    if ($n_removed) {
      $messenger->addMessage(t('Removed @count obsolete controlled vocabularies',
          ['@count' => $n_removed]));
    }
    if (!$n_transferred and !$n_removed) {
      $messenger->addMessage(t('No changes were needed'));
    }
  }
  catch (\Exception $e) {
    throw new UpdateException('Could not perform update: ' . $e->getMessage());
  }
}

/**
 * Adds missing 'path' setting to the 'record_id'
 * property in the 'chado_assay_type_default' field
 */
function tripal_chado_update_10412() {
  // This hook added by PR 2099
  $upgradable_types = ['chado_assay_type_default'];
  $upgradable_properties = ['record_id', 'assay_description'];
  tripal_chado_field_reload($upgradable_types, $upgradable_properties, TRUE);
}

/**
 * Adds chado_migrations to keep track of migrations applied to chado schema.
 */
function tripal_chado_update_10413() {
  $database = \Drupal::database();
  $schema = $database->schema();

  $table_name = 'chado_migrations';
  $table_schema = [
    'fields' => [
      'migration_id' => [
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
      'install_id' => [
        'type' => 'int',
        'not null' => TRUE,
      ],
      'version' => [
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
      ],
      'filename' => [
        'type' => 'text',
        'not null' => FALSE,
      ],
      'applied_on' => [
        'type' => 'varchar',
        'length' => 255,
      ],
      'success' => [
        'type' => 'int',
        'size' => 'tiny',
      ],
    ],
    'unique keys' => [
      'migration' => ['install_id', 'version'],
    ],
    'indexes' => [
      'status' => ['applied_on', 'success'],
    ],
    'foreign keys' => [
      'chado_installations' => [
        'table' => 'chado_installations',
        'columns' => [
          'install_id' => 'install_id'
        ],
      ],
    ],
    'primary key' => ['migration_id'],
  ];
  $schema->createTable($table_name, $table_schema);
}

/**
 * Adds the chado relationship field, PR 2128
 */
function tripal_chado_update_10414() {
  try {
    // Update collection configurations so that any content type
    // collections not yet imported will include the new relationship fields
    $collections = ['expression', 'general', 'genetic', 'genomic', 'germplasm'];
    updateContentTypeCollections($collections);

    // For any collections already imported, add all of the new relationship fields.
    addFieldFromYaml($config_dir . '/tripal.tripalfield_collection.expression_chado.yml',
      ['biosample_relationship']);
    addFieldFromYaml($config_dir . '/tripal.tripalfield_collection.general_chado.yml',
      ['analysis_relationship', 'contact_relationship', 'project_relationship', 'pub_relationship']);
    addFieldFromYaml($config_dir . '/tripal.tripalfield_collection.genetic_chado.yml',
      ['genetic_marker_relationship', 'phenotypic_marker_relationship', 'qtl_relationship', 'sequence_variant_relationship']);
    addFieldFromYaml($config_dir . '/tripal.tripalfield_collection.genomic_chado.yml',
      ['gene_relationship', 'genome_annotation_relationship', 'genome_assembly_relationship', 'genome_project_relationship', 'mrna_relationship']);
    addFieldFromYaml($config_dir . '/tripal.tripalfield_collection.germplasm_chado.yml',
      ['breeding_cross_relationship', 'germplasm_relationship', 'germplasm_variety_relationship', 'ril_relationship']);

  }
  catch (\Exception $e) {
    throw new UpdateException('Could not perform update: ' . $e->getMessage());
  }
}

/**
 * Updates to phylogenetic trees. PR 2223.
 */
function tripal_chado_update_10415() {
  try {
    $messenger = \Drupal::messenger();
    $chado = \Drupal::service('tripal_chado.database');
    $genomic_fields_yaml = __DIR__ . '/config/install/tripal.tripalfield_collection.genomic_chado.yml';

    // Adds a new CV term for storing the type of phylotree.
    $buddy_service = \Drupal::service('tripal_chado.chado_buddy');
    $cvterm_buddy = $buddy_service->createInstance('chado_cvterm_buddy', []);
    $term_values = [
      'db.name' => 'data',
      'cv.name' => 'EDAM',
      'dbxref.accession' => '1122',
      'cvterm.name' => 'Phylogenetic tree type',
      'cvterm.definition' => 'A label (text token) describing the type of a phylogenetic tree. [http://edamontology.org]',
    ];
    $chado_cvterm_record = $cvterm_buddy->upsertCvterm($term_values, []);
    $messenger->addMessage('Added "EDAM:Phylogenetic tree type" term');

    // Updates nonstandard terms for existing phylotrees, moving them
    // to properties. First get the two standard terms.
    $chado_buddy_records = $cvterm_buddy->getCvterm([
      'cv.name' => 'EDAM',
      'cvterm.name' => 'Phylogenetic tree',
    ]);
    $phylotree_bundle_id = $chado_buddy_records[0]->getValue('cvterm.cvterm_id');
    $chado_buddy_records = $cvterm_buddy->getCvterm([
      'cv.name' => 'EDAM',
      'cvterm.name' => 'Species tree',
    ]);
    // Get the term for the property.
    $speciestree_bundle_id = $chado_buddy_records[0]->getValue('cvterm.cvterm_id');
    $chado_buddy_records = $cvterm_buddy->getCvterm([
      'cv.name' => 'EDAM',
      'cvterm.name' => 'Phylogenetic tree type',
    ]);
    $property_id = $chado_buddy_records[0]->getValue('cvterm.cvterm_id');
    $query = $chado->select('1:phylotree', 't');
    $query->condition('type_id', [$phylotree_bundle_id, $speciestree_bundle_id], 'NOT IN');
    $query->fields('t', ['phylotree_id', 'type_id']);
    $needs_fixing = $query->execute();
    $n_updated = 0;
    foreach ($needs_fixing as $phylotree) {
      // Look up the cvterm name of the tree type.
      $chado_buddy_records = $cvterm_buddy->getCvterm([
        'cvterm.cvterm_id' => $phylotree->type_id,
      ]);
      $term_name = $chado_buddy_records[0]->getValue('cvterm.name');
      // Insert the existing term name as a property.
      $insert_fields = [
        'phylotree_id' => $phylotree->phylotree_id,
        'type_id' => $property_id,
        'value' => $term_name,
      ];
      $chado->insert('1:phylotreeprop')
        ->fields($insert_fields)
        ->execute();
      // Change the term of the phylotree record to the bundle term.
      $chado->update('1:phylotree')
        ->condition('phylotree_id', $phylotree->phylotree_id, '=')
        ->fields(['type_id' => $phylotree_bundle_id])
        ->execute();
      $n_updated++;
    }
    if ($n_updated) {
      $messenger->addMessage("Updated $n_updated phylotrees to use the standard CV term for this bundle");
    }

    // Add a field to access the 'Phylogenetic tree type' property. Only
    // adds this field if the genomic content type collection has been loaded.
    addFieldFromYaml($genomic_fields_yaml, ['phylotree_tree_type']);
    $messenger->addMessage('Added "Phylogenetic Tree Type" field');

    // There is a new bundle for species tree in the general collection.
    reloadContentTypeCollection('general');
    $messenger->addMessage('Added a "Species Tree" content type');

  }
  catch (\Exception $e) {
    throw new UpdateException('Could not update phylotree: ' . $e->getMessage());
  }
}
