version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: false
    config:
      threshold: 8
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 25
  method-count:
    enabled: false
    config:
      threshold: 20
  method-lines:
    enabled: false
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 6
  return-statements:
    enabled: true
    config:
      threshold: 6
  similar-code:
    enabled: false
    config:
      threshold: #language-specific defaults. overrides affect all languages.
  identical-code:
    enabled: false
    config:
      threshold: #language-specific defaults. overrides affect all languages.

# plugins:
#   eslint:
#     enabled: true
#     channel: "eslint-6"
#   rubocop:
#     enabled: true
#     channel: "rubocop-0-79"

exclude_patterns:
- "**/config/"
- "**/css/"
- "**/images/"
- "**/tests/"
- "**/docs/"
- "**/*.yml"
- "**/*.yaml"
- "**/*.md"
- "**/*.xml"
- "**/*.txt"
- "composer.json"
- "composer.lock"
- ".gitignore"
- "Dockerfile"
- ".github/"
- "tripaldocker/"
