- table: 'db'
  conditions:
    - column: 'name'
      value: 'AGRO'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/{db}_{accession}'
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'BS'
  update_column: 'description'
  existing_value: ''
  update_value: 'The Protein Feature Ontology is a structured controlled vocabulary for features of a protein sequence or structure.'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'EFO'
  update_column: 'urlprefix'
  existing_value: 'http://www.ebi.ac.uk/efo/{db}_{accession}'
  update_value: 'https://www.ebi.ac.uk/efo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'EFO'
  update_column: 'url'
  existing_value: 'http://www.ebi.ac.uk/efo/efo.owl'
  update_value: 'https://www.ebi.ac.uk/efo/'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'ERO'
  update_column: 'urlprefix'
  existing_value: 'http://purl.bioontology.org/ontology/ERO/{db}:{accession}'
  update_value: 'https://purl.bioontology.org/ontology/ERO/{db}:{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'ERO'
  update_column: 'url'
  existing_value: 'http://purl.bioontology.org/ontology/ERO'
  update_value: 'https://purl.bioontology.org/ontology/ERO'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'GO'
  update_column: 'description'
  existing_value: ''
  update_value: 'The mission of the GO Consortium is to develop a comprehensive, computational model of biological systems, ranging from the molecular to the organism level, across the multiplicity of species in the tree of life.'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'GO'
  update_column: 'urlprefix'
  existing_value: ''
  update_value: 'https://amigo.geneontology.org/amigo/term/{db}:{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'GO'
  update_column: 'url'
  existing_value: ''
  update_value: 'https://geneontology.org/'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'IAO'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/{db}_{accession}'
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'MOD'
  update_column: 'description'
  existing_value: ''
  update_value: 'Protein modification'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'MOD'
  update_column: 'urlprefix'
  existing_value: ''
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'MOD'
  update_column: 'url'
  existing_value: ''
  update_value: 'https://www.ebi.ac.uk/ols4/ontologies/mod'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'NCBITaxon'
  update_column: 'urlprefix'
  existing_value: 'https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id={accession}'
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'NCBITaxon'
  update_column: 'url'
  existing_value: 'http://www.berkeleybop.org/ontologies/ncbitaxon/'
  update_value: 'https://www.ebi.ac.uk/ols4/ontologies/ncbitaxon'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'NCIT'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/{db}_{accession}'
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'NCIT'
  update_column: 'url'
  existing_value: 'http://purl.obolibrary.org/obo/ncit.owl'
  update_value: 'https://www.ebi.ac.uk/ols4/ontologies/ncit'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'OBCS'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/{db}_{accession}'
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'OBI'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/{db}_{accession}'
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'OBI'
  update_column: 'url'
  existing_value: 'http://obi-ontology.org/page/Main_Page'
  update_value: 'https://obi-ontology.org/'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'OGI'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/{db}_{accession}'
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'OGI'
  update_column: 'url'
  existing_value: 'http://purl.bioontology.org/ontology/OGI'
  update_value: 'https://purl.bioontology.org/ontology/OGI'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'PBO'
  update_column: 'urlprefix'
  existing_value: 'https://agroportal.lirmm.fr/ontologies/PBO/PBO_{accession}'
  update_value: 'https://purl.obolibrary.org/obo/PBO_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'PMID'
  update_column: 'urlprefix'
  existing_value: 'http://www.ncbi.nlm.nih.gov/pubmed/{accession}'
  update_value: 'https://www.ncbi.nlm.nih.gov/pubmed/{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'PMID'
  update_column: 'url'
  existing_value: 'http://www.ncbi.nlm.nih.gov/pubmed'
  update_value: 'https://www.ncbi.nlm.nih.gov/pubmed'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'RNAMOD'
  update_column: 'description'
  existing_value: ''
  update_value: 'RNA modification'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'SBO'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/{db}_{accession}'
  update_value: 'https://www.ebi.ac.uk/ols4/ontologies/sbo/classes/http%253A%252F%252Fbiomodels.net%252FSBO%252F{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'SBO'
  update_column: 'url'
  existing_value: 'http://www.ebi.ac.uk/sbo/main/'
  update_value: 'https://www.ebi.ac.uk/ols4/ontologies/sbo'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'SIO'
  update_column: 'urlprefix'
  existing_value: 'http://semanticscience.org/resource/{db}_{accession}'
  update_value: 'https://semanticscience.org/resource/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'SIO'
  update_column: 'url'
  existing_value: 'http://sio.semanticscience.org/'
  update_value: 'https://sio.semanticscience.org/'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'SWO'
  update_column: 'urlprefix'
  existing_value: 'http://www.ebi.ac.uk/swo/{db}_{accession}'
  update_value: 'https://www.ebi.ac.uk/swo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'SWO'
  update_column: 'url'
  existing_value: 'http://purl.obolibrary.org/obo/swo'
  update_value: 'https://obofoundry.org/ontology/swo.html'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'TAXRANK'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/{db}_{accession}'
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'TAXRANK'
  update_column: 'url'
  existing_value: 'http://www.obofoundry.org/ontology/taxrank.html'
  update_value: 'https://www.obofoundry.org/ontology/taxrank.html'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'UO'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/UO_{accession}'
  update_value: 'https://purl.obolibrary.org/obo/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'UO'
  update_column: 'url'
  existing_value: 'http://purl.obolibrary.org/obo/uo'
  update_value: 'https://obofoundry.org/ontology/uo.html'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'data'
  update_column: 'urlprefix'
  existing_value: 'http://edamontology.org/{db}_{accession}'
  update_value: 'https://edamontology.org/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'data'
  update_column: 'url'
  existing_value: 'http://edamontology.org/page'
  update_value: 'https://edamontology.org/page'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'dc'
  update_column: 'urlprefix'
  existing_value: 'http://purl.org/dc/terms/{accession}'
  update_value: 'https://purl.org/dc/terms/{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'dc'
  update_column: 'url'
  existing_value: 'http://purl.org/dc/dcmitype/'
  update_value: 'https://www.dublincore.org/specifications/dublin-core/dcmi-terms/'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'dcterms'
  update_column: 'description'
  existing_value: ''
  update_value: ''
- table: 'db'
  conditions:
    - column: 'name'
      value: 'dcterms'
  update_column: 'urlprefix'
  existing_value: ''
  update_value: 'https://purl.org/dc/terms/{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'dcterms'
  update_column: 'url'
  existing_value: 'http://purl.org/dc/terms/'
  update_value: 'https://www.dublincore.org/specifications/dublin-core/dcmi-terms/'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'doi'
  update_column: 'description'
  existing_value: ''
  update_value: 'A DOI name is a digital identifier of an object, any object — physical, digital, or abstract.'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'doi'
  update_column: 'urlprefix'
  existing_value: ''
  update_value: 'https://doi.org/{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'doi'
  update_column: 'url'
  existing_value: ''
  update_value: 'https://www.doi.org'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'format'
  update_column: 'urlprefix'
  existing_value: 'http://edamontology.org/{db}_{accession}'
  update_value: 'https://edamontology.org/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'format'
  update_column: 'url'
  existing_value: 'http://edamontology.org/page'
  update_value: 'https://edamontology.org/page'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'gene_ontology'
  update_column: 'urlprefix'
  existing_value: ''
  update_value: 'https://amigo.geneontology.org/amigo/term/GO:{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'http'
  update_column: 'description'
  existing_value: ''
  update_value: 'This database is an unintended artifact of the Tripal obo importer'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'hydra'
  update_column: 'url'
  existing_value: 'http://www.w3.org/ns/hydra/core'
  update_value: 'https://www.hydra-cg.com/'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'null'
  update_column: 'urlprefix'
  existing_value: 'cv/lookup/{db}/{accession}'
  update_value: ''
- table: 'db'
  conditions:
    - column: 'name'
      value: 'operation'
  update_column: 'urlprefix'
  existing_value: 'http://edamontology.org/{db}_{accession}'
  update_value: 'https://edamontology.org/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'operation'
  update_column: 'url'
  existing_value: 'http://edamontology.org/page'
  update_value: 'https://edamontology.org/page'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'orcid'
  update_column: 'description'
  existing_value: ''
  update_value: 'ORCID is a free, unique, persistent identifier (PID) for individuals to use as they engage in research, scholarship, and innovation activities.'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'orcid'
  update_column: 'urlprefix'
  existing_value: ''
  update_value: 'https://orcid.org/{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'rdfs'
  update_column: 'urlprefix'
  existing_value: 'http://www.w3.org/2000/01/rdf-schema#{accession}'
  update_value: 'https://www.w3.org/TR/rdf11-schema/#ch_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'sep'
  update_column: 'description'
  existing_value: 'Sample processing and separation techniques.'
  update_value: 'Sample processing and separation techniques. (deprecated)'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'sep'
  update_column: 'urlprefix'
  existing_value: 'http://purl.obolibrary.org/obo/{db}_{accession}'
  update_value: ''
- table: 'db'
  conditions:
    - column: 'name'
      value: 'sep'
  update_column: 'url'
  existing_value: 'http://psidev.info/index.php?q=node/312'
  update_value: 'https://psidev.info/index.php?q=node/312'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'synonym_type'
  update_column: 'description'
  existing_value: ''
  update_value: 'Classification of the type of synonym. This ontology is defined by Tripal.'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'synonym_type'
  update_column: 'urlprefix'
  existing_value: ''
  update_value: 'cv/lookup/{db}/{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'synonym_type'
  update_column: 'url'
  existing_value: ''
  update_value: 'cv/lookup/synonym_type'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'topic'
  update_column: 'urlprefix'
  existing_value: 'http://edamontology.org/{db}_{accession}'
  update_value: 'https://edamontology.org/{db}_{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'topic'
  update_column: 'url'
  existing_value: 'http://edamontology.org/page'
  update_value: 'https://edamontology.org/page'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'wikipedia'
  update_column: 'description'
  existing_value: ''
  update_value: 'The Free Encyclopedia'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'wikipedia'
  update_column: 'urlprefix'
  existing_value: ''
  update_value: 'https://wikipedia.org/wiki/{accession}'
- table: 'db'
  conditions:
    - column: 'name'
      value: 'wikipedia'
  update_column: 'url'
  existing_value: ''
  update_value: 'https://www.wikipedia.org/'
