tripaldbx.settings:
  type: config_object
  mapping:
    reserved_schema_patterns:
      type: sequence
      label: 'Reserved schema patterns'
      sequence:
        type: string
    test_schema_base_names:
      type: sequence
      label: 'Test schema base names'
      sequence:
        type: string
