name: Discussion / Question
description: Discuss a topic / Ask for help.
body:
  - type: markdown
    attributes:
      value: |
        # Instructions
        Our intent is to use Github as an open forum to help community members connect.
        If you are looking to do any of the following, you are in the right place! and Thank You!
          - Ask for help/documentation/clarification of Tripal Functionality and Site Building/Management
          - Discuss controlled vocabulary terms for your data
          - Ask for input on site/module design questions
          - State your intent to develop a specific extension module
          - Really any type of discussion or question -we want to hear from you!
  - type: textarea
    id: discussion_question
    attributes:
      label: Discussion or Question
    validations:
        required: true