<?php

/**
 *
 * Implements hook_entity_load().
 */
function tripal_entities_entity_load($entities, $type) {
  foreach ($entities as $id => $entity) {

  }
}

/**
 *
 * Implements hook_entity_insert().
 */
function tripal_entities_entity_insert($entity, $type) {

}

/**
 *
 * Implements hook_entity_update().
 */
function tripal_entities_entity_update($entity, $type) {

}

/**
 *
 * Implements hook_entity_delete().
 */
function tripal_entities_entity_delete($entity, $type) {

}