rules:
  document-start: disable
  quoted-strings:
    quote-type: single
    required: true
  key-duplicates: {}
  trailing-spaces: {}
  colons: enable
  hyphens: enable
  octal-values:
    forbid-implicit-octal: true
