<?php

use Symfony\Component\Yaml\Yaml;
use Drupal\tripal_chado\ChadoCustomTables\ChadoCustomTable;

/**
 * @file
 * Contains tripal_file.module.
 */

/**
 * Creates the custom chado tables used by this module.
 *
 * @param string $chado_schema
 *   Optional. The chado schema where the custom table will live. If no
 *   schema is specified then the default schema is used.
 *
 * @return void
 *   No return value.
 */
function tripal_file_create_custom_chado_tables(string $chado_schema = NULL): void {
  $config = __DIR__ . '/config/other/tripal_file.custom_tables.yml';
  $schemas = Yaml::parseFile($config);
  foreach ($schemas as $table_name => $schema) {
    $customTable = new ChadoCustomTable($table_name, $chado_schema);
    // If the table already exists, e.g. for a migrated Tripal 3 site,
    // then only add missing columns, so that we preserve existing table content.
    $existing_schema = $customTable->getTableSchema();
    if ($existing_schema) {
      // @todo
    }
    else {
      $force = FALSE;
      $customTable->setTableSchema($schema, $force);
      $customTable->setLocked(TRUE);
    }
  }
}

/**
 * Deletes the custom chado tables used by this module.
 *
 * This is intended to be called when this module is uninstalled.
 *
 * @param string $chado_schema
 *   Optional. The chado schema where the custom tables live. If no
 *   schema is specified then the default schema is used.
 *
 * @return void
 *   No return value.
 */
function tripal_file_drop_custom_chado_tables(string $chado_schema = NULL): void {
  $config = __DIR__ . '/config/other/tripal_file.custom_tables.yml';
  $schemas = Yaml::parseFile($config);
  // Drop tables in reverse order of how they were created.
  $schemas = array_reverse($schemas);
  foreach (array_keys($schemas) as $table_name) {
    $customTable = new ChadoCustomTable($table_name, $chado_schema);
    $existing_schema = $customTable->getTableSchema();
    if ($existing_schema) {
      $customTable->delete();
    }
  }
}
