eimageprop:
    table: 'eimageprop'
    fields:
        eimageprop_id:
            size: 'big'
            type: 'serial'
            'not null': true
        eimage_id:
            type: 'int'
            'not null': true
        type_id:
            type: 'int'
            'not null': true
        value:
            type: 'text'
        rank:
            type: 'int'
            'not null': true
            default: 0
    'primary key':
        - 'eimageprop_id'
    'unique keys':
        fileprop_c1:
            - 'eimage_id'
            - 'type_id'
            - 'rank'
    indexes:
        eimageprop_idx1:
            - 'eimage_id'
        eimageprop_idx2:
            - 'type_id'
    'foreign keys':
        eimage:
            table: 'eimage'
            columns:
                eimage_id: 'eimage_id'
        cvterm:
            table: 'cvterm'
            columns:
                type_id: 'cvterm_id'
eimage_contact:
    table: 'eimage_contact'
    fields:
        eimage_contact_id:
            size: 'big'
            type: 'serial'
            'not null': true
        eimage_id:
            type: 'int'
            'not null': true
        contact_id:
            type: 'int'
        type_id:
            size: 'big'
            type: 'int'
        rank:
            type: 'int'
            'not null': true
            default: 0
    'primary key':
        - 'eimage_contact_id'
    'unique keys':
        eimage_contact_c1:
            - 'eimage_id'
            - 'contact_id'
            - 'type_id'
    'nulls not distinct':
        eimage_contact_c1: true
    indexes:
        eimage_contact_idx1:
            - 'eimage_id'
        eimage_contact_idx2:
            - 'contact_id'
        eimage_contact_idx3:
            - 'type_id'
    'foreign keys':
        eimage:
            table: 'eimage'
            columns:
                eimage_id: 'eimage_id'
        contact:
            table: 'contact'
            columns:
                contact_id: 'contact_id'
eimage_pub:
    table: 'eimage_pub'
    fields:
        eimage_pub_id:
            size: 'big'
            type: 'serial'
            'not null': true
        eimage_id:
            type: 'int'
            'not null': true
        pub_id:
            type: 'int'
        type_id:
            size: 'big'
            type: 'int'
        rank:
            type: 'int'
            'not null': true
            default: 0
    'primary key':
        - 'eimage_pub_id'
    'unique keys':
        eimage_pub_c1:
            - 'eimage_id'
            - 'pub_id'
            - 'type_id'
    'nulls not distinct':
        eimage_pub_c1: true
    indexes:
        eimage_pub_idx1:
            - 'eimage_id'
        eimage_pub_idx2:
            - 'pub_id'
        eimage_pub_idx3:
            - 'type_id'
    'foreign keys':
        eimage:
            table: 'eimage'
            columns:
                eimage_id: 'eimage_id'
        pub:
            table: 'pub'
            columns:
                pub_id: 'pub_id'
analysis_eimage:
    table: 'analysis_eimage'
    fields:
        analysis_eimage_id:
            size: 'big'
            type: 'serial'
            'not null': true
        analysis_id:
            size: 'big'
            type: 'int'
            'not null': true
        eimage_id:
            size: 'big'
            type: 'int'
            'not null': true
        type_id:
            size: 'big'
            type: 'int'
        rank:
            type: 'int'
            'not null': true
            default: 0
    'primary key':
        - 'analysis_eimage_id'
    'unique keys':
        analysis_eimage_c1:
            - 'analysis_id'
            - 'eimage_id'
            - 'type_id'
    'nulls not distinct':
        analysis_eimage_c1: true
    indexes:
        analysis_eimage_idx1:
            - 'analysis_id'
        analysis_eimage_idx2:
            - 'eimage_id'
        analysis_eimage_idx3:
            - 'type_id'
    'foreign keys':
        analysis:
            table: 'analysis'
            columns:
                analysis_id: 'analysis_id'
        eimage:
            table: 'eimage'
            columns:
                eimage_id: 'eimage_id'
        type_id:
            table: 'cvterm'
            columns:
                type_id: 'cvterm_id'
organism_eimage:
    table: 'organism_eimage'
    fields:
        organism_eimage_id:
            size: 'big'
            type: 'serial'
            'not null': true
        organism_id:
            size: 'big'
            type: 'int'
            'not null': true
        eimage_id:
            size: 'big'
            type: 'int'
            'not null': true
        type_id:
            size: 'big'
            type: 'int'
        rank:
            type: 'int'
            'not null': true
            default: 0
    'primary key':
        - 'organism_eimage_id'
    'unique keys':
        organism_eimage_c1:
            - 'organism_id'
            - 'eimage_id'
            - 'type_id'
    'nulls not distinct':
        organism_eimage_c1: true
    indexes:
        organism_eimage_idx1:
            - 'organism_id'
        organism_eimage_idx2:
            - 'eimage_id'
        organism_eimage_idx3:
            - 'type_id'
    'foreign keys':
        organism:
            table: 'organism'
            columns:
                organism_id: 'organism_id'
        eimage:
            table: 'eimage'
            columns:
                eimage_id: 'eimage_id'
        type_id:
            table: 'cvterm'
            columns:
                type_id: 'cvterm_id'
stock_eimage:
    table: 'stock_eimage'
    fields:
        stock_eimage_id:
            size: 'big'
            type: 'serial'
            'not null': true
        stock_id:
            size: 'big'
            type: 'int'
            'not null': true
        eimage_id:
            size: 'big'
            type: 'int'
            'not null': true
        type_id:
            size: 'big'
            type: 'int'
        rank:
            type: 'int'
            'not null': true
            default: 0
    'primary key':
        - 'stock_eimage_id'
    'unique keys':
        stock_eimage_c1:
            - 'stock_id'
            - 'eimage_id'
            - 'type_id'
    'nulls not distinct':
        stock_eimage_c1: true
    indexes:
        stock_eimage_idx1:
            - 'stock_id'
        stock_eimage_idx2:
            - 'eimage_id'
        stock_eimage_idx3:
            - 'type_id'
    'foreign keys':
        stock:
            table: 'stock'
            columns:
                stock_id: 'stock_id'
        eimage:
            table: 'eimage'
            columns:
                eimage_id: 'eimage_id'
        type_id:
            table: 'cvterm'
            columns:
                type_id: 'cvterm_id'
