eimageprop:
    table: 'eimageprop'
    fields:
        eimageprop_id:
            size: big
            type: serial
            'not null': true
        eimage_id:
            type: int
            'not null': true
        type_id:
            type: int
            'not null': true
        value:
            type: text
        rank:
            type: int
            'not null': true
            default: 0
    'primary key':
        - eimageprop_id
    'unique keys':
        fileprop_c1:
            - eimage_id
            - type_id
            - rank
    indexes:
        eimageprop_idx1:
            - eimage_id
        eimageprop_idx2:
            - type_id
    'foreign keys':
        eimage:
            table: eimage
            columns:
                eimage_id: eimage_id
        cvterm:
            table: cvterm
            columns:
                type_id: cvterm_id
stock_eimage:
    table: 'stock_eimage'
    fields:
        stock_eimage_id:
            size: big
            type: serial
            'not null': true
        stock_id:
            size: big
            type: int
            'not null': true
        eimage_id:
            size: big
            type: int
            'not null': true
        type_id:
            size: big
            type: int
        rank:
            type: int
            'not null': true
            default: 0
    'primary key':
        - stock_eimage_id
    'unique keys':
        stock_eimage_c1:
            - stock_id
            - eimage_id
            - type_id
    'nulls not distinct':
        stock_eimage_c1: true
    indexes:
        stock_eimage_idx1:
            - stock_id
        stock_eimage_idx2:
            - eimage_id
    'foreign keys':
        stock:
            table: stock
            columns:
                stock_id: stock_id
        eimage:
            table: eimage
            columns:
                eimage_id: eimage_id
        type_id:
            table: cvterm
            columns:
                type_id: cvterm_id
