name: 'Test Coverage on Drupal 11.1.x-dev + PHP 8.4'

on:
  push:
    branches:
      - '4.x'
  workflow_dispatch:
  pull_request:
    types: ['opened', 'synchronize']

permissions: read-all

jobs:
  run-tests:
    runs-on: 'ubuntu-latest'
    name: 'Test Coverage'

    steps:
      - name: 'Checkout Repository'
        uses: 'actions/checkout@v4'
      # Here we fully build a docker using the current checked out code
      # to ensure we have not broken the install/build process.
      - name: 'Build the Docker'
        run: |
          docker build --tag=tripaldocker:localdocker \
            --build-arg phpversion='8.4' \
            --build-arg drupalversion='11.1.x-dev' \
            --build-arg postgresqlversion='17' \
            --build-arg chadoschema='teacup' ./
      # Just spin up docker the good ol' fashion way.
      - name: 'Spin up Local Docker'
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal/web/modules/contrib/tripal \
            tripaldocker:localdocker
          docker exec tripaldocker service postgresql restart
      # Run tests within the docker and report both via text and clover.
      - name: 'Run Tests for Coverage'
        run: |
          docker exec tripaldocker service postgresql restart
          docker exec --workdir=/var/www/drupal/web/modules/contrib/tripal \
            tripaldocker phpunit --coverage-text \
              --coverage-clover /var/www/drupal/web/modules/contrib/tripal/clover.xml
      # Report the coverage results to QLTY Cloud.
      # This takes advantage of the --volume mapping when the container was created
      # to ensure we have access to clover.xml outside the docker container.
      - name: 'Publish code coverage to QLTY Cloud'
        uses: 'qltysh/qlty-action/coverage@v1'
        with:
          token: '${{ secrets.QLTY_COVERAGE_TOKEN }}'
          files: 'clover.xml'
          strip-prefix: '/var/www/drupal/web/modules/contrib/tripal'
