name: 'PHPUnit Matrixed'

on:
  workflow_dispatch:
  pull_request:
    types: ['opened', 'synchronize']

permissions: read-all

jobs:
  run-tests:
    runs-on: 'ubuntu-latest'

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
        pgsql-version:
          - '14'
          - '18'
        drupal-version:
          - '10.5.x-dev'
          - '10.6.x-dev'
          - '11.2.x-dev'
          - '11.3.x-dev'
          - '11.x-dev'
        exclude:
          # Only Drupal 11.x supports PHP 8.4+
          - php-version: '8.4'
            drupal-version: '10.5.x-dev'
          - php-version: '8.4'
            drupal-version: '10.6.x-dev'
          - php-version: '8.5'
            drupal-version: '10.5.x-dev'
          - php-version: '8.5'
            drupal-version: '10.6.x-dev'
          # Only Drupal 11.3+ supports PHP 8.5
          - php-version: '8.5'
            drupal-version: '10.5.x-dev'
          - php-version: '8.5'
            drupal-version: '10.6.x-dev'
          - php-version: '8.5'
            drupal-version: '11.2.x-dev'
          # Drupal 11+ requires at least php 8.3.
          - php-version: '8.2'
            drupal-version: '11.2.x-dev'
          - php-version: '8.2'
            drupal-version: '11.3.x-dev'
          - php-version: '8.2'
            drupal-version: '11.x-dev'
          # Drupal 11.x is the bleeding edge so only run it on the latest php.
          - php-version: '8.2'
            drupal-version: '11.x-dev'
          - php-version: '8.3'
            drupal-version: '11.x-dev'
          - php-version: '8.4'
            drupal-version: '11.x-dev'
          # Drupal 11+ requires at least Postgresql 16.
          - pgsql-version: '14'
            drupal-version: '11.2.x-dev'
          - pgsql-version: '15'
            drupal-version: '11.2.x-dev'
          - pgsql-version: '14'
            drupal-version: '11.3.x-dev'
          - pgsql-version: '15'
            drupal-version: '11.3.x-dev'
          - pgsql-version: '14'
            drupal-version: '11.x-dev'
          - pgsql-version: '15'
            drupal-version: '11.x-dev'
          # Drupal 11.x is the bleeding edge so only run it on the latest pgsql.
          - php-version: '8.4'
            pgsql-version: '14'
            drupal-version: '11.x-dev'
          - php-version: '8.5'
            pgsql-version: '14'
            drupal-version: '11.x-dev'
          # Exclude higher postgresql version from middle Drupal versions
          # This is done to reduce combinations; higher postgresql version
          # will be tested on merge to 4.x.
          # Note: Drupal 11.1 is already only tested on one postgresql
          # version since it requires 16+.
          - pgsql-version: '18'
            drupal-version: '10.5.x-dev'
          - pgsql-version: '18'
            drupal-version: '10.6.x-dev'
    steps:
      # Check out the repo
      - name: 'Checkout Repository'
        uses: 'actions/checkout@v6'
      - name: 'Run Automated testing'
        uses: 'tripal/test-tripal-action@v1.8'
        with:
          directory-name: 'tripal'
          modules: ''
          build-image: TRUE
          dockerfile: 'Dockerfile'
          php-version: ${{ matrix.php-version }}
          pgsql-version: ${{ matrix.pgsql-version }}
          drupal-version: ${{ matrix.drupal-version }}
