name: 'Assert Branch Naming Convention'
on: 'pull_request'

permissions: read-all

jobs:
  branch-naming-rules:
    runs-on: 'ubuntu-latest'
    steps:

      - name: "Validate branch name matches our standards"
        env:
          BRANCH_NAME: '${{ github.head_ref }}'
        run: |
          STANDARD='^tv4g[0-9]+-(issue){0,1}[0-9]+-?[a-zA-Z0-9_-]*$'

          if [[ ! "$BRANCH_NAME" =~ $STANDARD ]] && [[ ! "$BRANCH_NAME" == '4.x' ]]; then
            echo "::error::Branch name '$BRANCH_NAME' does not match our standard '$STANDARD'"
            exit 1
          fi

          echo "✅ Branch name '$BRANCH_NAME' matches our standard '$STANDARD' 🎉"
