name: 'Remove stale images from DockerHub'

on:
  # To allow manual run.
  workflow_dispatch:
  # schedule:
    # Run at 5am every morning, 1 hour after images are built.
    # - cron: '0 5 * * *'
  pull_request:

permissions: 'read-all'

jobs:
  execute-script:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout Repository'
        uses: 'actions/checkout@v6'

      - name: 'Cleanup Docker Hub Stale Drupal Images'
        env:
          USERNAME: '${{ secrets.DOCKERHUB_USERNAME }}'
          PASSWORD: '${{ secrets.DOCKERHUB_PASSWORD }}'
          DOCKER_HUB_COOKIE: '${{ secrets.DOCKERHUB_COOKIE }}'
          REPO: 'tripalproject/tripaldocker-drupal'
        run: bash .github/scripts/dockerhub_delete_stale.sh delete-untagged

      - name: 'Cleanup Docker Hub Stale Tripal Images'
        env:
          USERNAME: '${{ secrets.DOCKERHUB_USERNAME }}'
          PASSWORD: '${{ secrets.DOCKERHUB_PASSWORD }}'
          DOCKER_HUB_COOKIE: '${{ secrets.DOCKERHUB_COOKIE }}'
          REPO: 'tripalproject/tripaldocker'
        run: bash .github/scripts/dockerhub_delete_stale.sh delete-untagged
