name: 'Remove stale images from DockerHub'

on:
  # To allow manual run.
  workflow_dispatch:
  schedule:
    # Run at 5am every morning, 1 hour after images are built.
    - cron: '0 5 * * *'
  # This next trigger is temporary for testing!
  pull_request:

permissions: 'read-all'

jobs:
  clean_dockerhub:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v6'

      - name: 'Docker Hub Cleanup'
        uses: 'lostlink/docker-cleanup@v1.0.1'
        with:
          xcustom-patterns: '{:::invalidjson "latest": 90, "drupal": 90, "BUILT": 1}'
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN_RWD }}'
          repositories: 'tripaldocker-drupal,tripaldocker'
          pr-retention-days: 90
          sha-retention-days: 90
          verbose: true
          dry-run: true
